### PR TITLE
[WIP] GUI Controller skeleton

### PR DESCRIPTION
**Pull request by filipKov**
ready for GUI dev :)

### CODE REVIEW

**Review by TomasBakos — COMMENTED** [review]
Mohol by sa niekto z GUI k tomu vyjadrit a popripade mergnut.

**Review by matKovac — APPROVED** [review]

**Comment by TomasBakos** [comment]
Why are controller unrelated things being pushed into this pull request?

**Comment by mitas1** [comment]
Actually, our GUI team is not able to use git correctly, if you see commits in this PR :D I think, this PR before our pushes was not ready for merge. It actually does not do anything. So I marked this PR as WORK IN PROGRESS to add GUI related things. I do not think this is a problem. I though you need our GUI design before you can do anything else. And I think there are more problems we have to discussed personally.

**Comment by TomasBakos** [comment]
Yeah, probably my bad calling you guys out in this PR. I should have just merged it immidiately. And yeah, controller ppl have to wait for you design, i just think it should be in another PR, as graphic desing have little to do with controller stuff at least development-wise.

**Pull request merged**
